export const shopList = {
    "status": 1,
"result": {
        "total": "28",
        "pagesize": 10,
        "list": [
            {
                "id": "33",
                "title": "停车缴费",
                "subtitle": "",
                "thumb": "https://shopping.shimaoiot.com/attachment/images/2/2019/09/KlJiEiEXNJRj1JJEItnQJ4Ue1eJixj.jpg",
                "thumb_url": "a:0:{}",
                "marketprice": "0.00",
                "productprice": "0.00",
                "minprice": 0,
                "maxprice": 0,
                "isdiscount": "0",
                "isdiscount_time": "1568971200",
                "isdiscount_discounts": "{\"type\":0,\"default\":{\"option0\":\"\"},\"level1\":{\"option0\":\"\"}}",
                "sales": "0",
                "salesreal": "5",
                "total": "10000",
                "description": "",
                "bargain": "0",
                "type": "1",
                "ispresell": "0",
                "virtual": "0",
                "hasoption": "0",
                "video": "",
                "hascommission": "0",
                "nocommission": "0",
                "commission": "{\"type\":0}",
                "commission1_rate": "0.00",
                "commission1_pay": "0.00",
                "presellprice": "0.00",
                "seecommission": 0,
                "cansee": "0",
                "seetitle": ""
            },
            {
                "id": "25",
                "title": "预售卡",
                "subtitle": "",
                "thumb": "https://shopping.shimaoiot.com/attachment/images/2/2019/08/nhG4g899hl431a494G33Ip90kGkgXP.png",
                "thumb_url": "a:0:{}",
                "marketprice": "0.01",
                "productprice": "0.00",
                "minprice": 0.01,
                "maxprice": 0.01,
                "isdiscount": "0",
                "isdiscount_time": "1567046760",
                "isdiscount_discounts": "{\"type\":0,\"default\":{\"option0\":\"\"},\"level1\":{\"option0\":\"\"}}",
                "sales": "0",
                "salesreal": "1",
                "total": "0",
                "description": "",
                "bargain": "0",
                "type": "2",
                "ispresell": "0",
                "virtual": "0",
                "hasoption": "0",
                "video": "",
                "hascommission": "0",
                "nocommission": "0",
                "commission": "{\"type\":0}",
                "commission1_rate": "0.00",
                "commission1_pay": "0.00",
                "presellprice": "0.00",
                "seecommission": 0,
                "cansee": "0",
                "seetitle": ""
            }
        ],
    }
}
